= Общие сведения
:celesta: xref:celesta::1010_what_is_celesta.adoc[Celesta]
:mellophone: xref:mellophone::general.adoc[Mellophone]
:asciidoctor-od: https://courseorchestra.github.io/asciidoctor-open-document/[Asciidoctor Open Document]
:xylohpone: https://courseorchestra.github.io/xylophone/[Xylophone]
:lyra: https://github.com/CourseOrchestra/lyra[Lyra]
:hurdy-gurdy: https://github.com/CourseOrchestra/hurdy-gurdy[Hurdy-Gurdy]

Платформа КУРС -- это framework, разработанный компанией http://www.curs.ru[КУРС-ИТ] для создания широкого спектра веб-приложений и веб-служб (веб-сервисов).

Предлагаемая платформа -- оптимальное решение для разработки информационных систем, поддерживающих бизнес-процессы организаций, для которых отсутствуют готовые типовые решения или имеющиеся типовые решения не дотягивают до потребностей заказчика.

При разработке и развитии платформы мы ориентируемся на лучшее и наиболее распространенное в своем классе свободное программное обеспечение. Платформа активно разрабатывается с 2009 года, постоянно развивается, отражая современное состояние ИТ-технологий.

Платформа состоит из следующих элементов.

. xref:stack.adoc[] -- приоритетный набор технологий, которые мы используем в наших проектах. Единая техническая политика обеспечивает повышение эффективности процессов разработки и эксплуатации ПО. Отступление от стандартных технологий допускается в следующих случаях: (1) при наличии требований заказчика, (2) если использование других технологий дает радикальное улучшение характеристик продукта, (3) при необходимости развития платформы.
. xref:components.adoc[], разработанные в рамках платформы КУРС для повышения эффективности разработки:
. xref:examples.adoc[] технологий, предусмотренных платформой КУРС, для решения конкретных практических задач.

[[preimushhestva]]
== Преимущества использования платформы КУРС

. При использовании получаем классическое веб-приложение, состоящее из бэка и фронта, взаимодействующих через открытое API. Это позволяет создавать решения практически без ограничений по масштабированию.
. Соответствие бэка и фронта обеспечивается через кодогенерацию интерфейсов API, что делает невозможным их расхождение.
. Отсутствуют ограничения на использование интерфейсных компонент.
. Отсутствуют стандартные ограничения, связанные с использованием лицензируемого программного обеспечения.
. Снижен порог вхождения для разработчиков за счёт использования наиболее распространенных открытых технологий и документирования стандартных приемов применения этих технологий.